services:
  database:
    image: mariadb:latest
    container_name: mariadb-ct
    ports:
      - "3306:3306"
    volumes:
      - .data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}